### ISSUE TITLE
More Cases

### ISSUE THREAD

**Issue by timrijckaert** [rrousselGit/union#2]
Hi, 

I was wondering whether you could support more than 9 cases?
I see you have some kind of generator in place.

Other libs also have a max of 9 cases.
- [dartz](https://pub.dev/packages/dartz)
- [sealed_unions](https://pub.dev/packages/sealed_unions)

**Comment by rrousselGit** [comment]
I definitely can. How much do you think is desired?

The only thing to keep in mind is, more cases make the library grow exponentially. This as the consequence of  slowing the time out takes to start the app in debug mode

**Comment by nodinosaur** [comment]
Hi, 
If you would like to generate more than 9 cases, then I would suggest that you review your State/Model.
This is an interesting post on how you might do this [Sealed classes opened my mind](https://codeascraft.com/2018/04/12/sealed-classes-opened-my-mind/)

However, [Sealed Unions](https://github.com/fluttercommunity/dart_sealed_unions/blob/master/README.md) is a one-to-one port of [JavaSealedUnions](https://github.com/pakoito/JavaSealedUnions/blob/master/README.md) and reviewing the readme there might help answer some questions.

However, the idea of generating all the classes behind a `Union` is an interesting one 👍

**Comment by timrijckaert** [comment]
> If you would like to generate more than 9 cases, then I would suggest that you review your State/Model.

I disagree.
There is no clear cut point where say, 9 is the most cases you can have and then you have a problem with your architecture.

Let me explain our use case:
We would use this `Union` type for example to render different view types.
We have a `ListView` inside our app that can render more than 9 view types cases.

> I definitely can. How much do you think is desired?

Could it be possible to let the user generate the code on demand?
Instead of providing a fixed set of Unions inside the lib?

What do you think?

**Comment by rrousselGit** [comment]
> Could it be possible to let the user generate the code on demand?
Instead of providing a fixed set of Unions inside the lib?

Do you have an idea of what the syntax would look like?

Note that as a potential workaround you can have unions of unions:

```dart
Union2<Union2<A, B>, C> foo;

foo.join(
  (union) => union.join(
    (a) => AView(a),
    (b) => BView(b),
  ),
  (c) => CView(c),
);
```

Not ideal, but it's not too bad either.

**Comment by timrijckaert** [comment]
Good suggestion, but as you already pointed out not ideal and it feels like a limitation.

As for the syntax suggestion.
Ideally the end user should not know what the max type parameter are.
I know this might not be feasible 'cause of the translation in `first`, `second`, ..., maybe they should be more generic? 

As an inspiration look at the [sealed_unions_generator](https://github.com/BugsBunnyBR/sealed_unions_generator.dart)

````
part 'view_model.g.dart';
@Seal('WeatherState')
abstract class ViewModel {
  @Sealed()
  void phara(PharaViewModel vm);
  @Sealed()
  void xavier(XavierViewModel vm);
  @Sealed()
  void fatma(FatmaViewModel vm);
  ... othercases
}
```

Is this achievable?

**Comment by nodinosaur** [comment]
Which is what the article also suggests 😇

**Comment by rrousselGit** [comment]
I don't think that this package should try to solve sealed classes. 
Unions and Sealed classes are two different things.

What about:
- have this library generate Union2-Union20
- expose the first 6 on `package:union/union.dart`
- expose the others on `package:union/union_<number>.dart` and have people do:
  ```dart
  import 'package:union/union_20.dart';
  ```

This should be enough to make the analyzer _not die_.

**Comment by rrousselGit** [comment]
For example, the following is a sealed class in Dart:

```dart
class Sealed {
  Sealed._();
  factory Sealed() => Sealed._();

  int _property;
}
```

This class is sealed because it is both impossible to subclass and impossible to implement.

The subclassing is impossible because it exposes only a factory constructor.
And the implementation is impossible because it has one private property.

**Comment by nodinosaur** [comment]
What Sealed Unions (and I believe this lib) gives you is a `Closed Inheritance`, that means that you are only limited to all the inheritance types that are the defined in this Union and none else. 
Which means that when the compiler goes to them it knows exactly that there has to be _[say]_ four different types - this gives you some guarantees that you are assured that you have in-fact covered all possible cases.

**Comment by timrijckaert** [comment]
Thanks for the clarification.  

It seems like I would be using the unions as if they were sealed unions.
The libs all thought different I see now are quite similar too.

**Comment by rrousselGit** [comment]
Sealed_union use sealed class by using factories (Duplet) 
Union use non-sealed class, so that we can do https://github.com/rrousselGit/union#making-a-reusable-union

Making such subclass is critical to some architecture, such as `provider`.

**Comment by nodinosaur** [comment]
Except for the fact you can:
https://github.com/pakoito/RxSealedUnions/blob/master/README.md#subclassing
I might remind users that `Sealed Unions` is a one to one port of [RxSealedUnions](https://github.com/pakoito/RxSealedUnions)|[JavaSealedUnions](https://github.com/pakoito/JavaSealedUnions)

**Comment by rrousselGit** [comment]
That's not the same thing.

What you linked is a sealed class, not an union.

**Comment by rrousselGit** [comment]
Closing this for now. Since `union` switched to functions instead of classes for its implementation; combined with the fact that Dart doesn't support cool advanced typedefs, then adding more unions has negative side-effects.
