### ISSUE TITLE
Not able to use Union with Dart 2.9

### ISSUE THREAD

**Issue by mahmoudajawad** [rrousselGit/union#4]
![image](https://user-images.githubusercontent.com/316734/82014513-ce110b00-968d-11ea-8aa2-5dc683d34c49.png)

I'm unable to use your lib with Dart 2.9 with error:
```
The argument type 'TYPE_HERE' can't be assigned to the parameter type 'void Function(void Function(String), void Function(Photo), Object, Object, Object, Object, Object, Object, Object)'.
```

Can you confirm any related issues with this version of Dart.

**Comment by rrousselGit** [comment]
This is not how the library works.

You should instead write:

```dart
Comment(photo: Union2.first("foo"));
```

**Comment by mahmoudajawad** [comment]
I see. Thanks for explaining. I was taken quickly with what I found in the examples and didn't notice this part.
